// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfyDnuzPeOis4YYiq6CnXkSQnhdXyqsk',
    appId: '1:604512580588:web:815cbeeef12cd5638706c9',
    messagingSenderId: '604512580588',
    projectId: 'ttal-kkak',
    authDomain: 'ttal-kkak.firebaseapp.com',
    storageBucket: 'ttal-kkak.firebasestorage.app',
    measurementId: 'G-2PTZL418PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJKacPNniesDzbuI1cr0y5cYajhVQSq0',
    appId: '1:604512580588:android:fbcaa633e1c260308706c9',
    messagingSenderId: '604512580588',
    projectId: 'ttal-kkak',
    storageBucket: 'ttal-kkak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfCAOBJbtXBOYMozYUrMR59jP5GB8liU',
    appId: '1:604512580588:ios:6337dde29178f1d48706c9',
    messagingSenderId: '604512580588',
    projectId: 'ttal-kkak',
    storageBucket: 'ttal-kkak.firebasestorage.app',
    iosBundleId: 'com.sticky.ttalKkak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMfCAOBJbtXBOYMozYUrMR59jP5GB8liU',
    appId: '1:604512580588:ios:a01e4277667b7b258706c9',
    messagingSenderId: '604512580588',
    projectId: 'ttal-kkak',
    storageBucket: 'ttal-kkak.firebasestorage.app',
    iosBundleId: 'com.example.ttalKkak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvfyDnuzPeOis4YYiq6CnXkSQnhdXyqsk',
    appId: '1:604512580588:web:7cea89d29c7c4ba58706c9',
    messagingSenderId: '604512580588',
    projectId: 'ttal-kkak',
    authDomain: 'ttal-kkak.firebaseapp.com',
    storageBucket: 'ttal-kkak.firebasestorage.app',
    measurementId: 'G-SN6YL604ZZ',
  );
}
